# Generated by Django 4.0.4 on 2022-06-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
    ]
