# Generated by Django 4.0.4 on 2022-06-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_course_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(to='main.tag'),
        ),
    ]
